name: 'open_meteo_dbt'
version: '1.0.0'

profile: 'open_meteo_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  open_meteo_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table

